architect:
  - maxonfjvipon
docker:
  as_root: true
install:
  - "sudo apt-get update"
merge:
  commanders:
    - maxonfjvipon
  script: |-
    echo "### Validate composer.json and composer.lock"
    composer validate --strict
    echo "### Install dependencies"
    apt-get install php-xml php-mbstring -y
    composer install --prefer-dist --no-progress
    echo "### Run PHPStan"
    composer run-script phpstan
    echo "### Run tests"
    composer run-script test
    echo "### Check coverage"
    composer run-script coverage
release:
  script: |-
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    echo "### Validate composer.json and composer.lock"
    composer validate --strict
    echo "### Install dependencies"
    apt-get install php-xml php-mbstring -y
    composer install --prefer-dist --no-progress
    echo "### Run PHPStan"
    composer run-script phpstan
    echo "### Run tests"
    composer run-script test
    echo "### Check coverage"
    composer run-script coverage
